"""Items: messages, tool calls, reasoning and compaction."""

import json
from dataclasses import dataclass, field
from typing import Any, Literal, override

from mashumaro import field_options

from .base import (
    ExtensionFields,
    OpenResponsesModel,
    list_of,
    one_of,
    or_string,
    type_registry,
)
from .content import (
    MESSAGE_TEXT_PARTS,
    TEXT_PARTS,
    ContentPart,
    RefusalContent,
    join_text,
    parse_content,
)

__all__ = [
    "ITEM_TYPES",
    "CompactionItem",
    "FunctionCall",
    "FunctionCallOutput",
    "Item",
    "Message",
    "ReasoningItem",
    "UnknownItem",
    "parse_item",
]


@dataclass
class Message(OpenResponsesModel):
    """Message to or from the model."""

    type: Literal["message"] = "message"
    id: str | None = None
    status: str | None = None
    role: str = "assistant"
    content: list[ContentPart] = field(
        default_factory=list,
        metadata=field_options(deserialize=list_of(parse_content)),
    )
    phase: str | None = None

    @classmethod
    @override
    def __pre_deserialize__(cls, d: dict[Any, Any]) -> dict[Any, Any]:
        """Turn string content into a single text part."""
        match d:
            case {"content": str() as text}:
                role = d.get("role", "assistant")
                part_type = "output_text" if role == "assistant" else "input_text"
                d = {**d, "content": [{"type": part_type, "text": text}]}
        return super().__pre_deserialize__(d)

    @property
    def text(self) -> str:
        """Concatenated text of all text parts."""
        return join_text(self.content, MESSAGE_TEXT_PARTS)

    @property
    def refusal(self) -> str | None:
        """Concatenated refusal text, or `None` without a refusal."""
        return (
            "".join(
                part.refusal
                for part in self.content
                if isinstance(part, RefusalContent)
            )
            or None
        )


@dataclass
class FunctionCall(OpenResponsesModel):
    """Function call generated by the model."""

    type: Literal["function_call"] = "function_call"
    id: str | None = None
    call_id: str = ""
    name: str = ""
    arguments: str = ""
    status: str | None = None

    def parse_arguments(self) -> dict[str, Any]:
        """Decode the JSON arguments; empty arguments give `{}`."""
        match json.loads(self.arguments.strip() or "{}"):
            case dict() as arguments:
                return arguments
        raise ValueError(
            f"Expected the arguments to be a JSON object, got {self.arguments!r}"
        )


@dataclass
class FunctionCallOutput(OpenResponsesModel):
    """Result of a function call."""

    type: Literal["function_call_output"] = "function_call_output"
    id: str | None = None
    call_id: str = ""
    output: str | list[ContentPart] = field(
        default="",
        metadata=field_options(deserialize=or_string(list_of(parse_content))),
    )
    status: str | None = None


@dataclass
class ReasoningItem(OpenResponsesModel):
    """Reasoning as raw text, summary or encrypted content."""

    type: Literal["reasoning"] = "reasoning"
    id: str | None = None
    status: str | None = None
    summary: list[ContentPart] = field(
        default_factory=list,
        metadata=field_options(deserialize=list_of(parse_content)),
    )
    content: list[ContentPart] | None = field(
        default=None, metadata=field_options(deserialize=list_of(parse_content))
    )
    encrypted_content: str | None = None

    @property
    def summary_text(self) -> str:
        """Text of all summary parts."""
        return join_text(self.summary, TEXT_PARTS, "\n\n")

    @property
    def reasoning_text(self) -> str:
        """Raw reasoning text."""
        return join_text(self.content or (), TEXT_PARTS)


@dataclass
class CompactionItem(OpenResponsesModel):
    """Compacted conversation state from `compact()`."""

    type: Literal["compaction"] = "compaction"
    id: str | None = None
    encrypted_content: str = ""
    created_by: str | None = None


@dataclass(repr=False)
class UnknownItem(ExtensionFields, OpenResponsesModel):
    """Item type outside the spec, kept for round trips."""

    type: str = ""
    id: str | None = None
    status: str | None = None


type Item = (
    Message
    | FunctionCall
    | FunctionCallOutput
    | ReasoningItem
    | CompactionItem
    | UnknownItem
)
ITEM_TYPES = type_registry(
    Message, FunctionCall, FunctionCallOutput, ReasoningItem, CompactionItem
)
parse_item = one_of(ITEM_TYPES, UnknownItem, missing_type="message")
