"""Typed request parameters."""

from collections.abc import Mapping, Sequence
from typing import Any, Literal, Required, TypedDict

from .models import Item

__all__ = [
    "AllowedToolsParam",
    "AssistantMessageItemParam",
    "CompactionItemParam",
    "CreateResponseParams",
    "DeveloperMessageItemParam",
    "FunctionCallItemParam",
    "FunctionCallOutputItemParam",
    "FunctionToolParam",
    "InputFileContentParam",
    "InputImageContentParam",
    "InputItem",
    "InputItemParam",
    "InputTextContentParam",
    "InputVideoContentParam",
    "ItemReferenceParam",
    "JsonObjectResponseFormatParam",
    "JsonSchemaResponseFormatParam",
    "OutputTextContentParam",
    "ReasoningItemParam",
    "ReasoningParam",
    "ReasoningSummaryContentParam",
    "RefusalContentParam",
    "ResponseInput",
    "ResponseParams",
    "SpecificFunctionParam",
    "StreamOptionsParam",
    "StreamResponseParams",
    "SystemMessageItemParam",
    "TextFormatParam",
    "TextParam",
    "TextResponseFormatParam",
    "ToolChoiceParam",
    "ToolParam",
    "UrlCitationParam",
    "UserMessageItemParam",
]

type ItemStatusLiteral = Literal["in_progress", "completed", "incomplete"]
type ImageDetailLiteral = Literal["low", "high", "auto"]
type ToolChoiceModeLiteral = Literal["none", "auto", "required"]


class InputTextContentParam(TypedDict):
    """Text input."""

    type: Literal["input_text"]
    text: str


class InputImageContentParam(TypedDict, total=False):
    """Image input as URL or data URL."""

    type: Required[Literal["input_image"]]
    image_url: str | None
    detail: ImageDetailLiteral | None


class InputFileContentParam(TypedDict, total=False):
    """File input as URL or base64 `file_data`."""

    type: Required[Literal["input_file"]]
    filename: str | None
    file_data: str | None
    file_url: str | None


class InputVideoContentParam(TypedDict):
    """Video input as URL or data URL."""

    type: Literal["input_video"]
    video_url: str


class UrlCitationParam(TypedDict):
    """Citation of a web resource."""

    type: Literal["url_citation"]
    start_index: int
    end_index: int
    url: str
    title: str


class OutputTextContentParam(TypedDict, total=False):
    """Text previously generated by the model."""

    type: Required[Literal["output_text"]]
    text: Required[str]
    annotations: Sequence[UrlCitationParam]


class RefusalContentParam(TypedDict):
    """Refusal previously generated by the model."""

    type: Literal["refusal"]
    refusal: str


class ReasoningSummaryContentParam(TypedDict):
    """Part of a reasoning summary."""

    type: Literal["summary_text"]
    text: str


type UserContentParam = (
    InputTextContentParam | InputImageContentParam | InputFileContentParam
)
type AssistantContentParam = OutputTextContentParam | RefusalContentParam
type FunctionCallOutputContentParam = (
    InputTextContentParam
    | InputImageContentParam
    | InputFileContentParam
    | InputVideoContentParam
)


class UserMessageItemParam(TypedDict, total=False):
    """User message; `type` is optional."""

    type: Literal["message"]
    id: str | None
    role: Required[Literal["user"]]
    content: Required[str | Sequence[UserContentParam]]
    status: str | None


class SystemMessageItemParam(TypedDict, total=False):
    """System message."""

    type: Literal["message"]
    id: str | None
    role: Required[Literal["system"]]
    content: Required[str | Sequence[InputTextContentParam]]
    status: str | None


class DeveloperMessageItemParam(TypedDict, total=False):
    """Developer message."""

    type: Literal["message"]
    id: str | None
    role: Required[Literal["developer"]]
    content: Required[str | Sequence[InputTextContentParam]]
    status: str | None


class AssistantMessageItemParam(TypedDict, total=False):
    """Message previously generated by the model."""

    type: Literal["message"]
    id: str | None
    role: Required[Literal["assistant"]]
    content: Required[str | Sequence[AssistantContentParam]]
    phase: Literal["commentary", "final_answer"]
    status: str | None


class FunctionCallItemParam(TypedDict, total=False):
    """Function call previously generated by the model."""

    type: Required[Literal["function_call"]]
    id: str | None
    call_id: Required[str]
    name: Required[str]
    arguments: Required[str]
    status: ItemStatusLiteral | None


class FunctionCallOutputItemParam(TypedDict, total=False):
    """Result of a function call."""

    type: Required[Literal["function_call_output"]]
    id: str | None
    call_id: Required[str]
    output: Required[str | Sequence[FunctionCallOutputContentParam]]
    status: ItemStatusLiteral | None


class ReasoningItemParam(TypedDict, total=False):
    """Reasoning previously generated by the model."""

    type: Required[Literal["reasoning"]]
    id: str | None
    summary: Required[Sequence[ReasoningSummaryContentParam]]
    content: None
    encrypted_content: str | None


class CompactionItemParam(TypedDict, total=False):
    """Compaction item returned by `compact()`."""

    type: Required[Literal["compaction"]]
    id: str | None
    encrypted_content: Required[str]


class ItemReferenceParam(TypedDict, total=False):
    """Reference to a previous item by id."""

    type: Literal["item_reference"] | None
    id: Required[str]


type InputItemParam = (
    UserMessageItemParam
    | SystemMessageItemParam
    | DeveloperMessageItemParam
    | AssistantMessageItemParam
    | FunctionCallItemParam
    | FunctionCallOutputItemParam
    | ReasoningItemParam
    | CompactionItemParam
    | ItemReferenceParam
)

type InputItem = InputItemParam | Item | Mapping[str, Any]

type ResponseInput = str | Sequence[InputItem]


class FunctionToolParam(TypedDict, total=False):
    """Function the model can call."""

    type: Required[Literal["function"]]
    name: Required[str]
    description: str | None
    parameters: Mapping[str, Any] | None
    strict: bool


type ToolParam = FunctionToolParam | Mapping[str, Any]


class SpecificFunctionParam(TypedDict):
    """Forces a specific function."""

    type: Literal["function"]
    name: str


class AllowedToolsParam(TypedDict, total=False):
    """Restricts the tools the model may call."""

    type: Required[Literal["allowed_tools"]]
    tools: Required[Sequence[SpecificFunctionParam]]
    mode: ToolChoiceModeLiteral


# Arbitrary mappings allow choosing implementation-specific tools.
type ToolChoiceParam = (
    ToolChoiceModeLiteral
    | SpecificFunctionParam
    | AllowedToolsParam
    | Mapping[str, Any]
)


class TextResponseFormatParam(TypedDict):
    """Plain text output."""

    type: Literal["text"]


class JsonObjectResponseFormatParam(TypedDict):
    """Free-form JSON output."""

    type: Literal["json_object"]


class JsonSchemaResponseFormatParam(TypedDict, total=False):
    """JSON output matching a schema."""

    type: Required[Literal["json_schema"]]
    name: Required[str]
    description: str
    schema: Required[Mapping[str, Any]]
    strict: bool | None


type TextFormatParam = (
    TextResponseFormatParam
    | JsonObjectResponseFormatParam
    | JsonSchemaResponseFormatParam
)


class TextParam(TypedDict, total=False):
    """Text output settings."""

    format: TextFormatParam | None
    verbosity: Literal["low", "medium", "high"]


class ReasoningParam(TypedDict, total=False):
    """Reasoning settings, such as `effort` and `summary`."""

    effort: str | None
    summary: str | None


class StreamOptionsParam(TypedDict, total=False):
    """Options for streamed responses."""

    include_obfuscation: bool


class ResponseParams(TypedDict, total=False):
    """Request fields shared by HTTP and WebSocket; `None` values are omitted."""

    model: str | None
    input: ResponseInput | None
    instructions: str | None
    previous_response_id: str | None
    include: Sequence[str]
    tools: Sequence[ToolParam] | None
    tool_choice: ToolChoiceParam | None
    parallel_tool_calls: bool | None
    max_tool_calls: int | None
    text: TextParam | None
    reasoning: ReasoningParam | None
    metadata: Mapping[str, str] | None
    temperature: float | None
    top_p: float | None
    presence_penalty: float | None
    frequency_penalty: float | None
    top_logprobs: int | None
    max_output_tokens: int | None
    truncation: Literal["auto", "disabled"] | None
    store: bool | None
    service_tier: str | None
    safety_identifier: str | None
    prompt_cache_key: str | None


class CreateResponseParams(ResponseParams, total=False):
    """Parameters of `create()`."""

    background: bool | None


class StreamResponseParams(CreateResponseParams, total=False):
    """Parameters of `stream()`."""

    stream_options: StreamOptionsParam | None
